spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://144.24.87.198:5432/junny
    username: junny
    password: 1234
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate.format_sql: true
